name: "JackieO' Bar Mykonos"
favicon: null
layout_spectrum: 0.09716
typography_spectrum: 0.61315
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#31211f'
    - '#ffffff'
    - '#e38e6c'
    - '#378afc'
    - '#ffd296'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
